python/web-app/django-prac/pizzas/urls.py
from django.urls import path
from . import views

urlpatterns = [
        path('', views.index, name='index'),
        path('store/', views.store, name='store'),
        path('toppings/<int:store_id>/', views.store, name='store'),
]

python/web-app/django-prac/pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('pizzas.urls', 'pizzas'), namespace='pizzas')),
]

python/web-app/django-prac/pizzas/models.py
from django.db import models


class Pizza(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text


class Topping(models.Model):
    topic = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'toppings'

        def __str__(self):
            return self.text[:50] + "..."

python/web-app/django-prac/pizzas/views.py
from django.shortcuts import render
from .models import Pizza


def index(request):
    return render(request, 'pizzas/index.html')


def store(request, toppings_id):
    store = Pizza.objects.get(id=_id)
    toppings = store.entry_set.order_by('-date_added')
    context = {'store': store, 'toppings': toppings}
    return render(request, 'pizzas/store.html', context)

python/web-app/django-prac/pizzas/templates/pizzas/base.html
<p>
  <a href="{% url 'pizzas:index' %}">Pizzeria</a> -
  <a href="{% url 'pizzas:store' %}">Toppings</a>
</p>
{% block content %}{% endblock content %}

python/web-app/django-prac/pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content %}
<p>Learning Log helps you keep track of your learning, for any topic you're
learning about.</p>
{% endblock content %}

python/web-app/django-prac/pizzas/templates/pizzas/store.html
{% extends 'pizzas/base.html' %}

{% block content %}

<p>Stores: {{ stores }}</p>

<p>Toppings:</p>
<ul>
  {% for stores in store %}
    <li>
	<p>{{ stores.date_added|date:'M d, T H:i' }}</p>
	<p>{{ stores.text|linebreakes }}</p>
    </li>
  {% empty %}
    <li>No stores have been added yet.</li>
  {% endfor %}
</ul>

{% endblock content %}