python/web-app/applied-python-forum/forum/forum/urls.py
from django.contrib import admin
from django.urls import path
from forum import views

urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    path('topic/<int:topic_pk>/add_comment', views.CommentAdd.as_view()),
    path('topic/<int:pk>/', views.TopicView.as_view()),
]

python/web-app/applied-python-forum/forum/forum/models.py
from django.db import models


class Topic(models.Model):
    subject = models.CharField(u'Тема', max_length=255)
    text = models.TextField(u'Текст')
    creation_date = models.DateTimeField(
            u'Дата создания', auto_now_add=True)

    def __str__(self):
        return '{} | {}'.format(self.pk, self.subject)


class Comment(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.PROTECT)
    author_nick = models.CharField(u'Автор', max_length=255)
    text = models.TextField(u'Текст')
    reply_to = models.ForeignKey('forum.Comment', null=True, blank=True,
                                 on_delete=models.PROTECT)
    creation_date = models.DateTimeField(u'Дата создания', auto_now_add=True)

    def __str__(self):
        return "{} -> {}".format(self.author_nick, self.topic)

python/web-app/applied-python-forum/forum/forum/forms.py
from django.forms import ModelForm, HiddenInput
from forum.models import Comment


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['author_nick', 'text', 'topic']
        widgets = {
                'topic': HiddenInput()
        }

python/web-app/applied-python-forum/forum/forum/views.py
from django.shortcuts import render
from forum.models import Topic
from django.http import HttpResponse
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

from forum.forms import CommentForm


def hello_world(request):
    print(request.GET)
    a = request.GET.get('a', 0)
    b = request.GET.get('b', 0)
    rez = "Hello world!\na={}\nb={}".format(a, b)
    return HttpResponse(rez)


def index(request):
    topics = Topic.objects.all()[:10]
    context = {'topics': topics}
    return render(request, 'index.html', context)


class TopicView(DetailView):
    model = Topic
    template_name = 'topic.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_add_url'] = "/topic/{}/add_comment".format(
                context['topic'].id)
        return context


class CommentAdd(CreateView):
    template_name = 'comment_add.html'
    frorm_class = CommentForm

    def get_initial(self):
        return {
            "topic": self.kwargs['topic_pk']
        }

    def get_success_url(self):
        return "/topic/{}".format(self.kwargs['topic_pk'])

python/web-app/applied-python-forum/forum/forum/templates/comment_add.html
{% block content %}

<h2>Создать комменарий</h2>

<form action="{{ request.path }}" method="post">
    {% csrf_token %}
    {% for field in form %}
        <div class="form-group">
        {% if not field.is_hidden %}
            {{ field.label_tag }}<br />
        {% endif %}
        {{ field }}
        </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">Создать комментарий</button>
</form>

{% endblock %}

python/web-app/applied-python-forum/forum/forum/templates/forum/index.html
<h2>Список тем</h2>

<ul>
    {% for topic in topics %}
        <li><a href="topic/{{ topic.pk }}">{{ topic.subject }}</a></li>
    {% endfor %}
</ul>

python/web-app/applied-python-forum/forum/forum/templates/index.html
<h2>Список тем</h2>

<ul>
    {% for topic in topics %}
        <li><a href="topic/{{ topic.pk }}">{{ topic.subject }}</a></li>
    {% endfor %}
</ul>

python/web-app/applied-python-forum/forum/forum/templates/topic.html
{% block content %}

<h2>{{ topic.subject }}</h2>

<div class="well">
    {{ topic.text }}
</div>

{% for comment in topic.comment_set.all %}
<p>
    {{ comment.author_nick }}: {{ comment.text }}
    {% if comment.reply_to %}
        <b>| Reply to {{ comment.reply_to.author_nick }}</b>
    {% endif %}
</p>
{% endfor %}

<a href="{{ comment_add_url }}" type="button" class="btn btn-primary">Добавить</a>

{% endblock %}